### ISSUE TITLE
Create meta optimization.

### ISSUE THREAD

**Issue by martins-1992** [www-splitcells-net/net.splitcells.network#178]
# Overview
* [ ] Document history of reasoning for creating this.
* [x] Add such historic reasoning to development guidelines.
* [ ] Meta optimization is modeling a solution's history as an optimization problem.
* [ ] The consequence of that seems to be, that meta optimization is inherently a bit like offline optimization by default.
On the other hand, online optimization is needed and so meta optimization must support both interfaces.
This could be done via online/offline optimization adapter in worst case.
* [ ] Use derived constraints for communication between optimization.
* [ ] Use derived allocations for communication between optimization.
* [ ] Model meta optimization like a single table: step id -> optimization config constraints -> optimization config- > optimization events -> next set of optimization config constraints?
# Interesting Algorithms for Meta Optimization
* [ ] AI as basic optimizations?
* [ ] Statistics via derived allocations.
* [ ] Theorem Proving for Optimization Configuration: https://github.com/sosy-lab/java-smt
## AI Allocators
* Select group.
* Generate supplies proposal.
* Classify proposal.
* Choose proposal with 'best' classification.
## AI Proposals
* [ ] TODO

**Comment by martins-avots** [comment]
This will be done, when concrete requirements are present.
